### ISSUE TITLE
Using multiple Cartfiles

### ISSUE THREAD

**Issue by igorkulman** [pietbrauer/CarthageLicenseScript#5]
Would be nice if the script accepted multiple Cartfiles if you have more projects in your workspace (app project + "core" project).

**Comment by igorkulman** [comment]
I found a workaround using a `bash` script:

````bash
cp ../Project1/Cartfile.resolved Cartfile.resolved
cat ../Project2/Cartfile.resolved >> Cartfile.resolved
cat ../Project3/Cartfile.resolved >> Cartfile.resolved
awk '!a[$0]++' Cartfile.resolved > Cartfile.resolved
swift ./fetch_licenses.swift Cartfile.resolved
rm Cartfile.resolved
````

This bash script merges multiple `Cartfile`s into one, removes duplicities and calls the script on the resulting file.

**Comment by pietbrauer** [comment]
Nice job, would also be possible to read the first argument into the script as an array and do the same in Swift? I don't have the need personally but would appreciate a Pull Request if you are up for it?
