### ISSUE TITLE
Detecting License

### ISSUE THREAD

**Issue by igorkulman** [pietbrauer/CarthageLicenseScript#6]
Would it be possible to also detect license, like The MIT License (MIT), Apache License, etc?

**Comment by igorkulman** [comment]
Most licenses have their name of on the first line, but some normalisation is needed (stripping whitespace, etc).

**Comment by pietbrauer** [comment]
I think I would prefer using the GitHub License API https://developer.github.com/v3/licenses/#get-a-repositorys-license

**Comment by igorkulman** [comment]
Yes, look much better.

**Comment by pietbrauer** [comment]
I also think this is the way to go. Could you do a PR?

**Comment by igorkulman** [comment]
Sure, I will look into it.
